name: Vue CI

on:
  push:
    branches:
      - "**"
      - "!master"

# triggerBuildPipeline = 0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependencies
        run: npm install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run formatter tests
        run: npm run prettier:ci

      - name: Run lint tests
        run: npm run lint:ci

      # - name: Run unit tests
      #   run: npm run test:ci

      # - name: Run e2e Tests
      #   run: npm run all:e2e

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.61.0
        id: tag-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: minor
          RELEASE_BRANCHES: master
          PRERELEASE_SUFFIX: beta

      - name: Build Docker Image
        run: docker build . --file Dockerfile --build-arg GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} --tag ${{ github.repository }}:latest
